repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort
        args:
          - profile="black"
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args:
          - --max-line-length=100
          - --ignore-imports=yes
          - --duplicate-code
