repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort
        args:
          - profile="black"
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4'] 
